dist: xenial
sudo: required
language: python
cache: pip

python:
  - 3.5

before_install:
  - sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl

install: "pip install .[test]"

script: make

after_success:
  - codecov
